### ISSUE TITLE
License Discussion - Is MIT good?

### ISSUE THREAD

**Issue by MacyChan** [UBC-MDS/rlyrics#49]
Hi Guys, we are using [MIT license](https://github.com/UBC-MDS/rlyrics/blob/main/LICENSE.md). 
We have a couple of options [here](https://r-pkgs.org/license.html#license)
I found this [tool](https://choosealicense.com) for license select
And this [site](https://docs.python-guide.org/writing/license/) for license suggestions

1. If you want a permissive license so people can use your code with minimal restrictions, choose the MIT license with use_mit_license().

2. If you want a copyleft license so that all derivatives and bundles of your code are also open source, choose the GPLv3 license with use_gpl_license().

3. If your package primarily contains data, not code, and you want minimal restrictions, choose the CC0 license with use_cc0_license(). Or if you want to require attribution when your data is used, choose the CC BY license by calling use_ccby_license().

4. If you don’t want to make your code open source call use_proprietary_license(). Such packages can not be distributed by CRAN.

Maybe we can talk about the pros and cons for each, then select the one that is most suitable for our project?

Furthermore, I have a similar issue in our [python package](https://github.com/UBC-MDS/pylyrics/issues/73), but we can probably keep the conversation here!

**Comment by artanzand** [comment]
Hello,
I agree. Since the content of the two packages are the same, it is nice to keep them in one place for future reference. The license that we select will be applicable to both R and Python packages.

I think MIT license is a good option as it allows code with a permissive license to be freely copied, modified, and published, and the only restriction is that the license must be preserved. In case of our project we don't have any proprietary issues, and therefore, MIT seems fitting. What do you think?

**Comment by manju-abhinandana** [comment]
Yes, I agree that MIT license is a great choice as it allows to users to reuse and make modifications to the code to suit their purpose as long as the original copy the license is included.

**Comment by abhiket** [comment]
Yeah, please lets go ahead with MIT License. It is simple and is not very strict.

**Comment by artanzand** [comment]
Perfect! MIT it is then. We will keep it as is.
